#!/usr/bin/env bash
# Generator for dfn5b_files.rs — the DFN5B (ViT-H-14-378-quickgelu__dfn5b)
# external-data file enumeration baked into the compiled manifest.
#
# WHY a generator (plan P7.4 decision 2): the visual tower is an ONNX export
# with ~400 sibling external-data weight files (visual/visual.transformer.*,
# visual/onnx__*), and ort resolves them RELATIVE to visual/model.onnx — the
# whole set is load-bearing and must be pinned. Hand-typing 400 SHA-256 lines
# is error-prone, so we hash a verified local snapshot once and check in the
# result as a pure literal. The manifest stays a compiled literal in spirit:
# NO network and NO runtime directory discovery at app run time — discovery
# happens here, at author time, against a snapshot whose two graph onnx SHAs
# the author cross-checks against docs/SPIKE-P7-EMBED.md before committing.
#
# Enumerates every file under visual/ and textual/ (rknpu/armnn NPU variants
# excluded — we ship the CPU/GPU ort path only; the .cache dir is skipped).
#
# Usage:
#   ./gen_dfn5b_manifest.sh /path/to/ViT-H-14-378-quickgelu__dfn5b > dfn5b_files.rs
#
# Re-run only when the pinned revision changes; commit the regenerated file.

set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "usage: $0 <dfn5b-snapshot-dir>" >&2
    exit 2
fi

root="$1"
cd "$root"

cat <<'HEADER'
// @generated by crates/photoproof-core/src/runtime/gen_dfn5b_manifest.sh
// DO NOT EDIT BY HAND. Re-run the generator against a verified snapshot.
//
// DFN5B (ViT-H-14-378-quickgelu__dfn5b) file enumeration — every file under
// visual/ and textual/ (rknpu/armnn NPU variants excluded), each pinned to an
// exact SHA-256 + byte size. The visual tower's ONNX external-data weights
// (visual/onnx__*, visual/visual.transformer.*) are load-bearing: ort resolves
// them relative to visual/model.onnx, so the subdirectory layout is preserved
// on disk (plan P7.4 decision 1, path-preserving downloads).
//
// Tuple shape: (path, sha256, bytes).
pub(super) const DFN5B_FILES: &[(&str, &str, u64)] = &[
HEADER

# LC_ALL=C sort: a stable, locale-independent order so regenerations diff
# cleanly. find prunes the HF .cache metadata dir and any rknpu/armnn files.
find visual textual -type f \
    ! -path '*/.cache/*' \
    ! -iname '*rknpu*' \
    ! -iname '*armnn*' \
    | LC_ALL=C sort \
    | while read -r p; do
        sha=$(shasum -a 256 "$p" | awk '{print $1}')
        sz=$(stat -f '%z' "$p")
        printf '    ("%s", "%s", %s),\n' "$p" "$sha" "$sz"
    done

echo "];"
