/**
 * Viewport-first preview generation (OD-2) — the FRONTEND half. Pure +
 * DOM-free so the "which hashes do we ask the backend to make first" decision
 * unit-tests in isolation; the thin Grid.svelte hook feeds it the units in the
 * visible window on scroll-settle.
 *
 * Today the grid's thumbnails are generated by the ingest "preview" pass at
 * BACKFILL priority in roughly scan order. Right after a fresh scan or "Rebuild
 * all previews", scrolling to row 200 means waiting while the pump grinds
 * through rows 1-199. This module collects the hashes the user is actually
 * scrolled to whose thumbnail is NOT yet made (previewReady false) and hands
 * them to `ipc.prioritizePreviews`, which bumps just those preview passes to the
 * top interactive priority so they jump the queue.
 *
 * This complements the rest of the grid rather than fighting it: a generated
 * thumb already loads as an ordinary `photoproof://` `<img>` URL (and the graph
 * lens orders its own client-side LOAD via logic/thumbqueue). This call reorders
 * SERVER generation only, and ONLY for previews that don't exist yet — so it
 * never re-asks for a thumb that's already drawable.
 */
import type { DisplayUnit } from "../types/display";

/**
 * The visible-but-not-yet-generated hashes to prioritize, deduped, in order.
 * Both pair members count: a collapsed pair shows `primary`, an expanded pair
 * shows both, and either could be the cell the user is waiting on. A unit whose
 * `previewReady` is explicitly false has no thumb artifact yet (mid-scan, or a
 * fresh rebuild); `previewReady` absent/true means the thumb exists (or a test
 * fixture predates the flag) so there is nothing to make.
 */
export function visibleMissingHashes(units: readonly DisplayUnit[]): string[] {
  const out: string[] = [];
  const seen = new Set<string>();
  const consider = (hash: string, ready: boolean | undefined) => {
    // Only chase previews that don't exist yet; dedupe so a pair listed twice
    // (or a hash repeated across stacks) is asked for once.
    if (ready === false && !seen.has(hash)) {
      seen.add(hash);
      out.push(hash);
    }
  };
  for (const u of units) {
    consider(u.primary.hash, u.primary.previewReady);
    if (u.alt !== null) consider(u.alt.hash, u.alt.previewReady);
  }
  return out;
}

/** Two hash lists are equal iff same length and same order — the visible
 * window changes by sliding, so order is meaningful and cheap to compare. */
function sameHashes(a: readonly string[], b: readonly string[]): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false;
  return true;
}

/**
 * Debounces "viewport changed -> prioritize the visible missing previews" so a
 * fast scroll fires ONE backend call on settle rather than one per frame, and
 * skips the call entirely when the visible-missing set hasn't changed since the
 * last send (idle re-renders, or scrolling within an already-prioritized
 * window). `send` is injected (the ipc command) so the debounce + skip logic is
 * testable with fake timers and a mock.
 */
export class PreviewPrioritizer {
  private timer: ReturnType<typeof setTimeout> | undefined;
  private lastSent: string[] = [];

  constructor(
    private readonly send: (hashes: string[]) => void,
    private readonly delayMs = 120,
  ) {}

  /** Note the current visible units; schedules a debounced prioritize call. */
  notify(units: readonly DisplayUnit[]): void {
    const hashes = visibleMissingHashes(units);
    if (this.timer !== undefined) clearTimeout(this.timer);
    // Nothing visible is missing -> no call, and reset so a later identical set
    // still sends (the previous previews may have since been generated).
    if (hashes.length === 0) {
      this.lastSent = [];
      return;
    }
    this.timer = setTimeout(() => {
      this.timer = undefined;
      // Unchanged since the last send -> skip; the backend already promoted
      // exactly these and re-asking is wasted IPC.
      if (sameHashes(hashes, this.lastSent)) return;
      this.lastSent = hashes;
      this.send(hashes);
    }, this.delayMs);
  }

  /** Cancel any pending call and forget the last-sent set (a scope change:
   * the next window belongs to a different grid, prioritize it fresh). */
  reset(): void {
    if (this.timer !== undefined) clearTimeout(this.timer);
    this.timer = undefined;
    this.lastSent = [];
  }
}
